// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wrap.Data;

#nullable disable

namespace Wrap.Data.Migrations
{
    [DbContext(typeof(FilmProductionDbContext))]
    [Migration("20260330120456_EnitiesImagePathToNullable")]
    partial class EnitiesImagePathToNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Wrap.Data.Models.Cast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CastMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("076fd414-bd51-44a5-9d19-1f0a321e4d8e"),
                            Biography = "Stage and screen actor, passionate about drama and indie productions.",
                            BirthDate = new DateTime(1998, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elena",
                            Gender = 2,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Stoyanova",
                            Nickname = "Eli",
                            ProfileImagePath = "/img/profile/default-profile.png",
                            UserId = new Guid("5f279043-b38f-4f5f-b990-12fd90dcc30e")
                        },
                        new
                        {
                            Id = new Guid("dd6182e2-0e3b-4a74-8386-fdcfa8522a1f"),
                            Biography = "Film actor with a focus on action and thrillers.",
                            BirthDate = new DateTime(1995, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Georgi",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Ivanov",
                            ProfileImagePath = "/img/profile/default-profile.png",
                            UserId = new Guid("47a394d7-2ddb-4511-8355-a489dc8ea3f5")
                        },
                        new
                        {
                            Id = new Guid("80e32159-612c-4f6d-9eee-fe91afe5f619"),
                            Biography = "Aspiring actor, experienced in commercials and short films.",
                            BirthDate = new DateTime(2001, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Siyana",
                            Gender = 2,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Petrova",
                            Nickname = "Sisi",
                            ProfileImagePath = "/img/profile/default-profile.png",
                            UserId = new Guid("a77cc134-28f3-45d3-8e46-ba041a5371d0")
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.Crew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CrewMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            Biography = "Director of Photography focused on natural light and handheld storytelling.",
                            FirstName = "Alex",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Petrov",
                            Nickname = "AP/DP",
                            ProfileImagePath = "/img/profile/default-profile.png",
                            UserId = new Guid("a1093e45-6993-4d59-8e3f-4fe0b29e7dc5")
                        },
                        new
                        {
                            Id = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            Biography = "Production coordinator with experience in budgeting, call sheets and logistics.",
                            FirstName = "Maria",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Georgieva",
                            Nickname = "Maya",
                            ProfileImagePath = "/img/profile/default-profile.png",
                            UserId = new Guid("f704cf4b-b01a-4b5d-a052-7043caffd93e")
                        },
                        new
                        {
                            Id = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            Biography = "Sound recordist and boom operator. Location sound, ADR planning, and on-set workflow.",
                            FirstName = "Ivan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dimitrov",
                            ProfileImagePath = "/img/profile/default-profile.png",
                            UserId = new Guid("5150238b-cd37-482d-ab11-ef66bae0128f")
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.CrewSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("CrewSkills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 1
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 2
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 20
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 21
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 50
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 51
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 60
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 62
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 70
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 71
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 80
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000012"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 82
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.Infrastructure.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .HasMaxLength(27)
                        .HasColumnType("nvarchar(27)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Wrap.Data.Models.Infrastructure.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1093e45-6993-4d59-8e3f-4fe0b29e7dc5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-crew-con-1",
                            Email = "alex.petrov@wrap.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALEX.PETROV@WRAP.LOCAL",
                            NormalizedUserName = "ALEX.PETROV",
                            PhoneNumber = "+359888000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "seed-crew-sec-1",
                            TwoFactorEnabled = false,
                            UserName = "alex.petrov"
                        },
                        new
                        {
                            Id = new Guid("f704cf4b-b01a-4b5d-a052-7043caffd93e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-crew-con-2",
                            Email = "maria.georgieva@wrap.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARIA.GEORGIEVA@WRAP.LOCAL",
                            NormalizedUserName = "MARIA.GEORGIEVA",
                            PhoneNumber = "+359888000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "seed-crew-sec-2",
                            TwoFactorEnabled = false,
                            UserName = "maria.georgieva"
                        },
                        new
                        {
                            Id = new Guid("5150238b-cd37-482d-ab11-ef66bae0128f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-crew-con-3",
                            Email = "ivan.dimitrov@wrap.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN.DIMITROV@WRAP.LOCAL",
                            NormalizedUserName = "IVAN.DIMITROV",
                            PhoneNumber = "+359888000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "seed-crew-sec-3",
                            TwoFactorEnabled = false,
                            UserName = "ivan.dimitrov"
                        },
                        new
                        {
                            Id = new Guid("5f279043-b38f-4f5f-b990-12fd90dcc30e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-cast-con-1",
                            Email = "elena.stoyanova@wrap.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ELENA.STOYANOVA@WRAP.LOCAL",
                            NormalizedUserName = "ELENA.STOYANOVA",
                            PhoneNumber = "+359888100001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "seed-cast-sec-1",
                            TwoFactorEnabled = false,
                            UserName = "elena.stoyanova"
                        },
                        new
                        {
                            Id = new Guid("47a394d7-2ddb-4511-8355-a489dc8ea3f5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-cast-con-2",
                            Email = "georgi.ivanov@wrap.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GEORGI.IVANOV@WRAP.LOCAL",
                            NormalizedUserName = "GEORGI.IVANOV",
                            PhoneNumber = "+359888100002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "seed-cast-sec-2",
                            TwoFactorEnabled = false,
                            UserName = "georgi.ivanov"
                        },
                        new
                        {
                            Id = new Guid("a77cc134-28f3-45d3-8e46-ba041a5371d0"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-cast-con-3",
                            Email = "siyana.petrova@wrap.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SIYANA.PETROVA@WRAP.LOCAL",
                            NormalizedUserName = "SIYANA.PETROVA",
                            PhoneNumber = "+359888100003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "seed-cast-sec-3",
                            TwoFactorEnabled = false,
                            UserName = "siyana.petrova"
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.ProductionCast", b =>
                {
                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CastMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProductionId", "CastMemberId");

                    b.HasIndex("CastMemberId");

                    b.ToTable("ProductionsCastMembers");

                    b.HasData(
                        new
                        {
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            CastMemberId = new Guid("076fd414-bd51-44a5-9d19-1f0a321e4d8e"),
                            Role = "Detective Ivanov"
                        },
                        new
                        {
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            CastMemberId = new Guid("dd6182e2-0e3b-4a74-8386-fdcfa8522a1f"),
                            Role = "Witness"
                        },
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d01"),
                            CastMemberId = new Guid("80e32159-612c-4f6d-9eee-fe91afe5f619"),
                            Role = "Lead Actress"
                        },
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d02"),
                            CastMemberId = new Guid("076fd414-bd51-44a5-9d19-1f0a321e4d8e"),
                            Role = "Private Investigator"
                        },
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d02"),
                            CastMemberId = new Guid("dd6182e2-0e3b-4a74-8386-fdcfa8522a1f"),
                            Role = "Antagonist"
                        },
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            CastMemberId = new Guid("dd6182e2-0e3b-4a74-8386-fdcfa8522a1f"),
                            Role = "Supporting Role"
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.ProductionCrew", b =>
                {
                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.HasKey("ProductionId", "CrewMemberId");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("ProductionsCrewMembers");

                    b.HasData(
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d09"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 1
                        },
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d09"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 20
                        },
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d09"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 70
                        },
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d06"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 1
                        },
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d05"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 21
                        },
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 71
                        },
                        new
                        {
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 82
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.SceneCast", b =>
                {
                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CastMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SceneId", "CastMemberId");

                    b.HasIndex("CastMemberId");

                    b.ToTable("ScenesCastMembers");

                    b.HasData(
                        new
                        {
                            SceneId = new Guid("11111111-bbbb-bbbb-bbbb-111111111111"),
                            CastMemberId = new Guid("076fd414-bd51-44a5-9d19-1f0a321e4d8e"),
                            Role = "Detective Ivanov"
                        },
                        new
                        {
                            SceneId = new Guid("11111111-bbbb-bbbb-bbbb-111111111111"),
                            CastMemberId = new Guid("dd6182e2-0e3b-4a74-8386-fdcfa8522a1f"),
                            Role = "Witness"
                        },
                        new
                        {
                            SceneId = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            CastMemberId = new Guid("076fd414-bd51-44a5-9d19-1f0a321e4d8e"),
                            Role = "Detective Ivanov"
                        },
                        new
                        {
                            SceneId = new Guid("44444444-bbbb-bbbb-bbbb-444444444444"),
                            CastMemberId = new Guid("80e32159-612c-4f6d-9eee-fe91afe5f619"),
                            Role = "Lead Actress"
                        },
                        new
                        {
                            SceneId = new Guid("66666666-bbbb-bbbb-bbbb-666666666666"),
                            CastMemberId = new Guid("076fd414-bd51-44a5-9d19-1f0a321e4d8e"),
                            Role = "Private Investigator"
                        },
                        new
                        {
                            SceneId = new Guid("66666666-bbbb-bbbb-bbbb-666666666666"),
                            CastMemberId = new Guid("dd6182e2-0e3b-4a74-8386-fdcfa8522a1f"),
                            Role = "Antagonist"
                        },
                        new
                        {
                            SceneId = new Guid("88888888-bbbb-bbbb-bbbb-888888888888"),
                            CastMemberId = new Guid("dd6182e2-0e3b-4a74-8386-fdcfa8522a1f"),
                            Role = "Supporting Role"
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.SceneCrew", b =>
                {
                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.HasKey("SceneId", "CrewMemberId");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("ScenesCrewMembers");

                    b.HasData(
                        new
                        {
                            SceneId = new Guid("11111111-bbbb-bbbb-bbbb-111111111111"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 1
                        },
                        new
                        {
                            SceneId = new Guid("11111111-bbbb-bbbb-bbbb-111111111111"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 20
                        },
                        new
                        {
                            SceneId = new Guid("11111111-bbbb-bbbb-bbbb-111111111111"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 70
                        },
                        new
                        {
                            SceneId = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 1
                        },
                        new
                        {
                            SceneId = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 21
                        },
                        new
                        {
                            SceneId = new Guid("33333333-bbbb-bbbb-bbbb-333333333333"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 22
                        },
                        new
                        {
                            SceneId = new Guid("33333333-bbbb-bbbb-bbbb-333333333333"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 71
                        },
                        new
                        {
                            SceneId = new Guid("44444444-bbbb-bbbb-bbbb-444444444444"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 1
                        },
                        new
                        {
                            SceneId = new Guid("44444444-bbbb-bbbb-bbbb-444444444444"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 20
                        },
                        new
                        {
                            SceneId = new Guid("55555555-bbbb-bbbb-bbbb-555555555555"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 30
                        },
                        new
                        {
                            SceneId = new Guid("55555555-bbbb-bbbb-bbbb-555555555555"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 72
                        },
                        new
                        {
                            SceneId = new Guid("66666666-bbbb-bbbb-bbbb-666666666666"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 7
                        },
                        new
                        {
                            SceneId = new Guid("66666666-bbbb-bbbb-bbbb-666666666666"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 20
                        },
                        new
                        {
                            SceneId = new Guid("77777777-bbbb-bbbb-bbbb-777777777777"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 2
                        },
                        new
                        {
                            SceneId = new Guid("77777777-bbbb-bbbb-bbbb-777777777777"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 70
                        },
                        new
                        {
                            SceneId = new Guid("88888888-bbbb-bbbb-bbbb-888888888888"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 21
                        },
                        new
                        {
                            SceneId = new Guid("88888888-bbbb-bbbb-bbbb-888888888888"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 71
                        },
                        new
                        {
                            SceneId = new Guid("99999999-bbbb-bbbb-bbbb-999999999999"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 1
                        },
                        new
                        {
                            SceneId = new Guid("99999999-bbbb-bbbb-bbbb-999999999999"),
                            CrewMemberId = new Guid("5bc88034-ac2f-49cf-b39c-20a54ae09c50"),
                            RoleType = 20
                        },
                        new
                        {
                            SceneId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-aaaaaaaaaaaa"),
                            CrewMemberId = new Guid("8019d5fc-23a7-49d8-80ac-b3edd8a7e398"),
                            RoleType = 7
                        },
                        new
                        {
                            SceneId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-aaaaaaaaaaaa"),
                            CrewMemberId = new Guid("ec228657-ad62-4e57-a749-8becaccce6dd"),
                            RoleType = 73
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.Production", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("StatusEndDate")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("StatusStartDate")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("StatusType")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Productions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            Budget = 1000.00m,
                            Description = "This is a test",
                            StatusEndDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusStartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusType = 1,
                            Thumbnail = "/img/thumbnail/default-thumbnail.png",
                            Title = "Test Film"
                        },
                        new
                        {
                            Id = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d01"),
                            Budget = 250000.00m,
                            Description = "A neo-noir mystery unfolding over one sleepless night.",
                            StatusEndDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusStartDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusType = 2,
                            Thumbnail = "/img/thumbnail/default-thumbnail.png",
                            Title = "Midnight Dreams"
                        },
                        new
                        {
                            Id = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d02"),
                            Budget = 120000.00m,
                            Description = "A coming-of-age drama about ambition, fear, and first love.",
                            StatusEndDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusStartDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusType = 5,
                            Thumbnail = "/img/thumbnail/default-thumbnail.png",
                            Title = "Paper Planes"
                        },
                        new
                        {
                            Id = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            Budget = 180000.00m,
                            Description = "A comedic behind-the-scenes story about a cursed film set.",
                            StatusEndDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusStartDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusType = 3,
                            Thumbnail = "/img/thumbnail/default-thumbnail.png",
                            Title = "The Last Take"
                        },
                        new
                        {
                            Id = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d04"),
                            Budget = 750000.00m,
                            Description = "A sci-fi thriller set in a near-future megacity.",
                            StatusEndDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusStartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusType = 4,
                            Thumbnail = "/img/thumbnail/default-thumbnail.png",
                            Title = "Neon Skyline"
                        },
                        new
                        {
                            Id = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d05"),
                            Budget = 90000.00m,
                            Description = "A documentary journey following musicians on the road.",
                            StatusEndDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusStartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusType = 6,
                            Thumbnail = "/img/thumbnail/default-thumbnail.png",
                            Title = "Wild Tracks"
                        },
                        new
                        {
                            Id = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d06"),
                            Budget = 60000.00m,
                            Description = "A character study about burnout and reinvention.",
                            StatusEndDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusStartDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusType = 9,
                            Thumbnail = "/img/thumbnail/default-thumbnail.png",
                            Title = "On Hold"
                        },
                        new
                        {
                            Id = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d07"),
                            Budget = 320000.00m,
                            Description = "A tense drama about fixing a film before the deadline.",
                            StatusEndDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusStartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusType = 10,
                            Thumbnail = "/img/thumbnail/default-thumbnail.png",
                            Title = "Reshoot Season"
                        },
                        new
                        {
                            Id = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d08"),
                            Budget = 140000.00m,
                            Description = "An art-house film exploring memory through sound and color.",
                            StatusEndDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusStartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusType = 14,
                            Thumbnail = "/img/thumbnail/default-thumbnail.png",
                            Title = "Color & Noise"
                        },
                        new
                        {
                            Id = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d09"),
                            Budget = 210000.00m,
                            Description = "A finished film preparing for its festival circuit debut.",
                            StatusEndDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusStartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusType = 19,
                            Thumbnail = "/img/thumbnail/default-thumbnail.png",
                            Title = "Festival Run"
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.ProductionAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId", "AssetType");

                    b.ToTable("ProductionsAssets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-cccc-cccc-cccc-111111111111"),
                            AssetType = 1,
                            Description = "Basic scene coverage and camera beats.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            Title = "Storyboard v1",
                            UploadedAt = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-cccc-cccc-cccc-222222222222"),
                            AssetType = 2,
                            Description = "Lighting references and overall vibe.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            Title = "Moodboard - Visual Tone",
                            UploadedAt = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            AssetType = 3,
                            Description = "Primary palette for day interiors.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            Title = "Color Palette - Day Scenes",
                            UploadedAt = new DateTime(2026, 3, 2, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-cccc-cccc-cccc-444444444444"),
                            AssetType = 4,
                            Description = "Reference stills for framing and composition.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d01"),
                            Title = "Reference Frames Pack",
                            UploadedAt = new DateTime(2026, 3, 2, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-cccc-cccc-cccc-555555555555"),
                            AssetType = 1,
                            Description = "Action sequence beats and movement.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d01"),
                            Title = "Storyboard - Chase Sequence",
                            UploadedAt = new DateTime(2026, 3, 3, 9, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-cccc-cccc-cccc-666666666666"),
                            AssetType = 99,
                            Description = "Draft PDF with lens & shot notes.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d01"),
                            Title = "Shot List Draft",
                            UploadedAt = new DateTime(2026, 3, 3, 9, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77777777-cccc-cccc-cccc-777777777777"),
                            AssetType = 2,
                            Description = "Neon, fog, wet streets.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d02"),
                            Title = "Moodboard - Night Atmosphere",
                            UploadedAt = new DateTime(2026, 3, 3, 9, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("88888888-cccc-cccc-cccc-888888888888"),
                            AssetType = 3,
                            Description = "Cold shadows with warm practicals.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d02"),
                            Title = "Color Palette - Night Scenes",
                            UploadedAt = new DateTime(2026, 3, 4, 14, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-cccc-cccc-cccc-999999999999"),
                            AssetType = 4,
                            Description = "Props and set dressing ideas.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d02"),
                            Title = "Set Dressing References",
                            UploadedAt = new DateTime(2026, 3, 4, 14, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-cccc-cccc-cccc-aaaaaaaaaaaa"),
                            AssetType = 1,
                            Description = "Final sequence beats and transitions.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            Title = "Storyboard - Finale",
                            UploadedAt = new DateTime(2026, 3, 4, 14, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-cccc-cccc-cccc-bbbbbbbbbbbb"),
                            AssetType = 99,
                            Description = "Scouting photos for final location.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            Title = "Location Photos",
                            UploadedAt = new DateTime(2026, 3, 4, 14, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AssetType = 4,
                            Description = "Wardrobe references for key characters.",
                            FilePath = "/img/assets/default-asset.png",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            Title = "Costume References",
                            UploadedAt = new DateTime(2026, 3, 4, 14, 5, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SceneName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SceneNumber")
                        .HasColumnType("int");

                    b.Property<int>("SceneType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId", "SceneNumber");

                    b.ToTable("Scenes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-bbbb-bbbb-bbbb-111111111111"),
                            Description = "A tense meeting sets the stakes for the story.",
                            Location = "Downtown Coffee Shop",
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            SceneName = "Coffee Shop Conversation",
                            SceneNumber = 1,
                            SceneType = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            Description = "Fast-paced pursuit through the city streets.",
                            Location = "Main Boulevard",
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            SceneName = "Street Chase",
                            SceneNumber = 2,
                            SceneType = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-bbbb-bbbb-bbbb-333333333333"),
                            Description = "Key evidence is discovered.",
                            Location = "Character A Apartment",
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            SceneName = "Apartment Reveal",
                            SceneNumber = 3,
                            SceneType = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-bbbb-bbbb-bbbb-444444444444"),
                            Description = "A suspect breaks under pressure.",
                            Location = "Police Station",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d01"),
                            SceneName = "Interrogation Room",
                            SceneNumber = 1,
                            SceneType = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-bbbb-bbbb-bbbb-555555555555"),
                            Description = "Conflict escalates with a dramatic skyline backdrop.",
                            Location = "Office Building Rooftop",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d01"),
                            SceneName = "Rooftop Argument",
                            SceneNumber = 2,
                            SceneType = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-bbbb-bbbb-bbbb-666666666666"),
                            Description = "A mysterious figure appears in the shadows.",
                            Location = "Old Town Alley",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d02"),
                            SceneName = "Night Alley Encounter",
                            SceneNumber = 1,
                            SceneType = 2
                        },
                        new
                        {
                            Id = new Guid("77777777-bbbb-bbbb-bbbb-777777777777"),
                            Description = "The team plans the next move.",
                            Location = "Garage Workshop",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d02"),
                            SceneName = "Workshop Planning",
                            SceneNumber = 2,
                            SceneType = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-bbbb-bbbb-bbbb-888888888888"),
                            Description = "Emotional turning point for the lead character.",
                            Location = "City Hospital",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            SceneName = "Hospital Corridor",
                            SceneNumber = 1,
                            SceneType = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-bbbb-bbbb-bbbb-999999999999"),
                            Description = "Two characters reconcile after a fallout.",
                            Location = "Central Park",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            SceneName = "Park Reunion",
                            SceneNumber = 2,
                            SceneType = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-aaaaaaaaaaaa"),
                            Description = "Closing moment with a hopeful sunrise.",
                            Location = "Cliffside Overlook",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            SceneName = "Finale: Sunrise Cliff",
                            SceneNumber = 3,
                            SceneType = 2
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.Script", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastEditedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RevisionType")
                        .HasColumnType("int");

                    b.Property<int>("StageType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId")
                        .IsUnique();

                    b.ToTable("Scripts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36ca9b58-d902-4195-bf80-2e6518ad3c6d"),
                            LastEditedAt = new DateTime(2026, 3, 26, 13, 22, 5, 0, DateTimeKind.Utc),
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            StageType = 2,
                            Title = "Test Screenplay"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            LastEditedAt = new DateTime(2026, 3, 26, 13, 22, 5, 0, DateTimeKind.Utc),
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d01"),
                            StageType = 2,
                            Title = "Midnight Dreams — Draft"
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-4444-5555-666666666666"),
                            LastEditedAt = new DateTime(2026, 3, 26, 13, 22, 5, 0, DateTimeKind.Utc),
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d02"),
                            RevisionType = 3,
                            StageType = 7,
                            Title = "Paper Planes — Shooting Script"
                        },
                        new
                        {
                            Id = new Guid("33333333-4444-5555-6666-777777777777"),
                            LastEditedAt = new DateTime(2026, 3, 26, 13, 22, 5, 0, DateTimeKind.Utc),
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03"),
                            RevisionType = 2,
                            StageType = 8,
                            Title = "The Last Take — Blue Revision"
                        },
                        new
                        {
                            Id = new Guid("44444444-5555-6666-7777-888888888888"),
                            LastEditedAt = new DateTime(2026, 3, 26, 13, 22, 5, 0, DateTimeKind.Utc),
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d04"),
                            StageType = 1,
                            Title = "Neon Skyline — Outline"
                        },
                        new
                        {
                            Id = new Guid("55555555-6666-7777-8888-999999999999"),
                            LastEditedAt = new DateTime(2026, 3, 26, 13, 22, 5, 0, DateTimeKind.Utc),
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d05"),
                            RevisionType = 4,
                            StageType = 4,
                            Title = "Wild Tracks — Polish"
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.ScriptBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BlockType")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Metadata")
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("ScriptId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScriptId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("ScriptBlocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65a5a61f-204d-4274-be48-bf4b440ff6a1"),
                            BlockType = 1,
                            Content = "INT. COFFEE SHOP - DAY",
                            CreatedAt = new DateTime(2026, 3, 9, 13, 22, 5, 0, DateTimeKind.Utc),
                            LastModifiedAt = new DateTime(2026, 3, 9, 13, 22, 5, 0, DateTimeKind.Utc),
                            OrderIndex = 0,
                            ScriptId = new Guid("36ca9b58-d902-4195-bf80-2e6518ad3c6d")
                        },
                        new
                        {
                            Id = new Guid("c5cc8272-c35d-4b4b-bb31-137df7fe86d5"),
                            BlockType = 3,
                            Content = "A bustling morning crowd. Steam rises from espresso machines.",
                            CreatedAt = new DateTime(2026, 3, 9, 13, 22, 5, 0, DateTimeKind.Utc),
                            LastModifiedAt = new DateTime(2026, 3, 9, 13, 22, 5, 0, DateTimeKind.Utc),
                            OrderIndex = 1,
                            ScriptId = new Guid("36ca9b58-d902-4195-bf80-2e6518ad3c6d")
                        },
                        new
                        {
                            Id = new Guid("befd3f37-d237-4e46-8a21-e08704c6ef00"),
                            BlockType = 4,
                            Content = "JOHN",
                            CreatedAt = new DateTime(2026, 3, 9, 13, 22, 5, 0, DateTimeKind.Utc),
                            LastModifiedAt = new DateTime(2026, 3, 9, 13, 22, 5, 0, DateTimeKind.Utc),
                            OrderIndex = 2,
                            ScriptId = new Guid("36ca9b58-d902-4195-bf80-2e6518ad3c6d")
                        },
                        new
                        {
                            Id = new Guid("3bed994a-cbee-4d60-b22f-a922b82eb841"),
                            BlockType = 7,
                            Content = "I'll have a double espresso. Make it strong.",
                            CreatedAt = new DateTime(2026, 3, 9, 13, 22, 5, 0, DateTimeKind.Utc),
                            LastModifiedAt = new DateTime(2026, 3, 9, 13, 22, 5, 0, DateTimeKind.Utc),
                            OrderIndex = 3,
                            ScriptId = new Guid("36ca9b58-d902-4195-bf80-2e6518ad3c6d")
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.ShootingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.ToTable("ShootingDays");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-aaaa-aaaa-aaaa-100000000001"),
                            Date = new DateTime(2026, 3, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Day 1: Coffee shop scene coverage.",
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928")
                        },
                        new
                        {
                            Id = new Guid("10000000-aaaa-aaaa-aaaa-100000000002"),
                            Date = new DateTime(2026, 3, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Day 2: Pickups and insert shots.",
                            ProductionId = new Guid("819f7100-5b1d-4eee-8b82-8e4084ef0928")
                        },
                        new
                        {
                            Id = new Guid("20000000-aaaa-aaaa-aaaa-200000000001"),
                            Date = new DateTime(2026, 3, 23, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Night exterior sequence.",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d01")
                        },
                        new
                        {
                            Id = new Guid("20000000-aaaa-aaaa-aaaa-200000000002"),
                            Date = new DateTime(2026, 3, 24, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Studio interiors + dialogue scenes.",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d01")
                        },
                        new
                        {
                            Id = new Guid("30000000-aaaa-aaaa-aaaa-300000000001"),
                            Date = new DateTime(2026, 3, 26, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "School hallway + classroom scenes.",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d02")
                        },
                        new
                        {
                            Id = new Guid("40000000-aaaa-aaaa-aaaa-400000000001"),
                            Date = new DateTime(2026, 3, 28, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Stage scenes and rehearsal coverage.",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03")
                        },
                        new
                        {
                            Id = new Guid("40000000-aaaa-aaaa-aaaa-400000000002"),
                            Date = new DateTime(2026, 3, 29, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Close-ups, alt takes, safety shots.",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d03")
                        },
                        new
                        {
                            Id = new Guid("50000000-aaaa-aaaa-aaaa-500000000001"),
                            Date = new DateTime(2026, 3, 31, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "City night montage (neon locations).",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d04")
                        },
                        new
                        {
                            Id = new Guid("60000000-aaaa-aaaa-aaaa-600000000001"),
                            Date = new DateTime(2026, 4, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Outdoor travel sequence.",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d05")
                        },
                        new
                        {
                            Id = new Guid("70000000-aaaa-aaaa-aaaa-700000000001"),
                            Date = new DateTime(2026, 4, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Planned shoot (project currently on hold).",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d06")
                        },
                        new
                        {
                            Id = new Guid("80000000-aaaa-aaaa-aaaa-800000000001"),
                            Date = new DateTime(2026, 4, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Reshoot day: continuity fixes + inserts.",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d07")
                        },
                        new
                        {
                            Id = new Guid("90000000-aaaa-aaaa-aaaa-900000000001"),
                            Date = new DateTime(2026, 4, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "B-roll day for post-production needs.",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d08")
                        },
                        new
                        {
                            Id = new Guid("a0000000-aaaa-aaaa-aaaa-a00000000001"),
                            Date = new DateTime(2026, 4, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Press / promo shoot day.",
                            ProductionId = new Guid("2a6d6e6d-5a3a-4b7c-9e9a-0b0f5e5c4d09")
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.ShootingDayScene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShootingDayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("ShootingDayId", "SceneId")
                        .IsUnique();

                    b.ToTable("ShootingDaysScenes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-cccc-cccc-cccc-b10000000001"),
                            Order = 1,
                            SceneId = new Guid("11111111-bbbb-bbbb-bbbb-111111111111"),
                            ShootingDayId = new Guid("10000000-aaaa-aaaa-aaaa-100000000001")
                        },
                        new
                        {
                            Id = new Guid("b1000000-cccc-cccc-cccc-b10000000002"),
                            Order = 2,
                            SceneId = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            ShootingDayId = new Guid("10000000-aaaa-aaaa-aaaa-100000000001")
                        },
                        new
                        {
                            Id = new Guid("b1000000-cccc-cccc-cccc-b10000000003"),
                            Order = 1,
                            SceneId = new Guid("33333333-bbbb-bbbb-bbbb-333333333333"),
                            ShootingDayId = new Guid("10000000-aaaa-aaaa-aaaa-100000000002")
                        },
                        new
                        {
                            Id = new Guid("b2000000-cccc-cccc-cccc-b20000000001"),
                            Order = 1,
                            SceneId = new Guid("44444444-bbbb-bbbb-bbbb-444444444444"),
                            ShootingDayId = new Guid("20000000-aaaa-aaaa-aaaa-200000000001")
                        },
                        new
                        {
                            Id = new Guid("b2000000-cccc-cccc-cccc-b20000000002"),
                            Order = 1,
                            SceneId = new Guid("55555555-bbbb-bbbb-bbbb-555555555555"),
                            ShootingDayId = new Guid("20000000-aaaa-aaaa-aaaa-200000000002")
                        },
                        new
                        {
                            Id = new Guid("b3000000-cccc-cccc-cccc-b30000000001"),
                            Order = 1,
                            SceneId = new Guid("66666666-bbbb-bbbb-bbbb-666666666666"),
                            ShootingDayId = new Guid("30000000-aaaa-aaaa-aaaa-300000000001")
                        },
                        new
                        {
                            Id = new Guid("b3000000-cccc-cccc-cccc-b30000000002"),
                            Order = 2,
                            SceneId = new Guid("77777777-bbbb-bbbb-bbbb-777777777777"),
                            ShootingDayId = new Guid("30000000-aaaa-aaaa-aaaa-300000000001")
                        },
                        new
                        {
                            Id = new Guid("b4000000-cccc-cccc-cccc-b40000000001"),
                            Order = 1,
                            SceneId = new Guid("88888888-bbbb-bbbb-bbbb-888888888888"),
                            ShootingDayId = new Guid("40000000-aaaa-aaaa-aaaa-400000000001")
                        },
                        new
                        {
                            Id = new Guid("b4000000-cccc-cccc-cccc-b40000000002"),
                            Order = 2,
                            SceneId = new Guid("99999999-bbbb-bbbb-bbbb-999999999999"),
                            ShootingDayId = new Guid("40000000-aaaa-aaaa-aaaa-400000000001")
                        },
                        new
                        {
                            Id = new Guid("b4000000-cccc-cccc-cccc-b40000000003"),
                            Order = 1,
                            SceneId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-aaaaaaaaaaaa"),
                            ShootingDayId = new Guid("40000000-aaaa-aaaa-aaaa-400000000002")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wrap.Data.Models.Cast", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wrap.Data.Models.Crew", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wrap.Data.Models.CrewSkill", b =>
                {
                    b.HasOne("Wrap.Data.Models.Crew", "CrewMember")
                        .WithMany("Skills")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewMember");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.ProductionCast", b =>
                {
                    b.HasOne("Wrap.Data.Models.Cast", "CastMember")
                        .WithMany("CastMemberProductions")
                        .HasForeignKey("CastMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithMany("ProductionCastMembers")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CastMember");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.ProductionCrew", b =>
                {
                    b.HasOne("Wrap.Data.Models.Crew", "CrewMember")
                        .WithMany("CrewMemberProductions")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithMany("ProductionCrewMembers")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewMember");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.SceneCast", b =>
                {
                    b.HasOne("Wrap.Data.Models.Cast", "CastMember")
                        .WithMany("CastMemberScenes")
                        .HasForeignKey("CastMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.Scene", "Scene")
                        .WithMany("SceneCastMembers")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CastMember");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.SceneCrew", b =>
                {
                    b.HasOne("Wrap.Data.Models.Crew", "CrewMember")
                        .WithMany("CrewMemberScenes")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.Scene", "Scene")
                        .WithMany("SceneCrewMembers")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewMember");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Wrap.Data.Models.ProductionAsset", b =>
                {
                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithMany("ProductionAssets")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.Scene", b =>
                {
                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithMany("Scenes")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.Script", b =>
                {
                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithOne("Script")
                        .HasForeignKey("Wrap.Data.Models.Script", "ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.ScriptBlock", b =>
                {
                    b.HasOne("Wrap.Data.Models.Script", "Script")
                        .WithMany("ScriptBlocks")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Script");
                });

            modelBuilder.Entity("Wrap.Data.Models.ShootingDay", b =>
                {
                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithMany("ShootingDays")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.ShootingDayScene", b =>
                {
                    b.HasOne("Wrap.Data.Models.Scene", "Scene")
                        .WithMany("ShootingDayScenes")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.ShootingDay", "ShootingDay")
                        .WithMany("ShootingDayScenes")
                        .HasForeignKey("ShootingDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");

                    b.Navigation("ShootingDay");
                });

            modelBuilder.Entity("Wrap.Data.Models.Cast", b =>
                {
                    b.Navigation("CastMemberProductions");

                    b.Navigation("CastMemberScenes");
                });

            modelBuilder.Entity("Wrap.Data.Models.Crew", b =>
                {
                    b.Navigation("CrewMemberProductions");

                    b.Navigation("CrewMemberScenes");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Wrap.Data.Models.Production", b =>
                {
                    b.Navigation("ProductionAssets");

                    b.Navigation("ProductionCastMembers");

                    b.Navigation("ProductionCrewMembers");

                    b.Navigation("Scenes");

                    b.Navigation("Script");

                    b.Navigation("ShootingDays");
                });

            modelBuilder.Entity("Wrap.Data.Models.Scene", b =>
                {
                    b.Navigation("SceneCastMembers");

                    b.Navigation("SceneCrewMembers");

                    b.Navigation("ShootingDayScenes");
                });

            modelBuilder.Entity("Wrap.Data.Models.Script", b =>
                {
                    b.Navigation("ScriptBlocks");
                });

            modelBuilder.Entity("Wrap.Data.Models.ShootingDay", b =>
                {
                    b.Navigation("ShootingDayScenes");
                });
#pragma warning restore 612, 618
        }
    }
}
