// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wrap.Data;

#nullable disable

namespace Wrap.Data.Migrations
{
    [DbContext(typeof(FilmProductionDbContext))]
    partial class FilmProductionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Wrap.Data.Models.Cast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CastMembers");
                });

            modelBuilder.Entity("Wrap.Data.Models.Crew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("Wrap.Data.Models.CrewSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("CrewSkills");
                });

            modelBuilder.Entity("Wrap.Data.Models.Infrastructure.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.ProductionCast", b =>
                {
                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CastMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductionId", "CastMemberId");

                    b.HasIndex("CastMemberId");

                    b.ToTable("ProductionsCastMembers");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.ProductionCrew", b =>
                {
                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductionId", "CrewMemberId");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("ProductionsCrewMembers");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.SceneCast", b =>
                {
                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CastMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SceneId", "CastMemberId");

                    b.HasIndex("CastMemberId");

                    b.ToTable("ScenesCastMembers");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.SceneCrew", b =>
                {
                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SceneId", "CrewMemberId");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("ScenesCrewMembers");
                });

            modelBuilder.Entity("Wrap.Data.Models.Production", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("StatusEndDate")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("StatusStartDate")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("StatusType")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Productions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("809f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            Budget = 1000.00m,
                            Description = "This is a test",
                            StatusEndDate = new DateTime(2026, 2, 13, 20, 23, 51, 404, DateTimeKind.Utc).AddTicks(6920),
                            StatusStartDate = new DateTime(2026, 2, 8, 20, 23, 51, 404, DateTimeKind.Utc).AddTicks(6920),
                            StatusType = 1,
                            Title = "Test Film"
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.ProductionAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.ToTable("ProductionsAssets");
                });

            modelBuilder.Entity("Wrap.Data.Models.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SceneName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SceneNumber")
                        .HasColumnType("int");

                    b.Property<int>("SceneType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("Wrap.Data.Models.Script", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("LastEditedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId")
                        .IsUnique();

                    b.ToTable("Scripts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36ca9b58-d902-4195-bf80-2e6518ad3c6d"),
                            LastEditedAt = new DateTime(2026, 2, 8, 20, 23, 51, 405, DateTimeKind.Utc).AddTicks(1050),
                            ProductionId = new Guid("809f7100-5b1d-4eee-8b82-8e4084ef0928"),
                            Title = "Test Screenplay"
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.ScriptBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BlockType")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Metadata")
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("ScriptId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScriptId", "OrderIndex");

                    b.ToTable("ScriptBlocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65a5a61f-204d-4274-be48-bf4b440ff6a1"),
                            BlockType = 1,
                            Content = "INT. COFFEE SHOP - DAY",
                            CreatedAt = new DateTime(2026, 2, 8, 20, 23, 51, 404, DateTimeKind.Utc).AddTicks(9970),
                            LastModifiedAt = new DateTime(2026, 2, 8, 20, 23, 51, 404, DateTimeKind.Utc).AddTicks(9970),
                            OrderIndex = 0,
                            ScriptId = new Guid("36ca9b58-d902-4195-bf80-2e6518ad3c6d")
                        },
                        new
                        {
                            Id = new Guid("c5cc8272-c35d-4b4b-bb31-137df7fe86d5"),
                            BlockType = 3,
                            Content = "A bustling morning crowd. Steam rises from espresso machines.",
                            CreatedAt = new DateTime(2026, 2, 8, 20, 23, 51, 404, DateTimeKind.Utc).AddTicks(9980),
                            LastModifiedAt = new DateTime(2026, 2, 8, 20, 23, 51, 404, DateTimeKind.Utc).AddTicks(9980),
                            OrderIndex = 1,
                            ScriptId = new Guid("36ca9b58-d902-4195-bf80-2e6518ad3c6d")
                        },
                        new
                        {
                            Id = new Guid("befd3f37-d237-4e46-8a21-e08704c6ef00"),
                            BlockType = 4,
                            Content = "JOHN",
                            CreatedAt = new DateTime(2026, 2, 8, 20, 23, 51, 404, DateTimeKind.Utc).AddTicks(9980),
                            LastModifiedAt = new DateTime(2026, 2, 8, 20, 23, 51, 404, DateTimeKind.Utc).AddTicks(9980),
                            OrderIndex = 2,
                            ScriptId = new Guid("36ca9b58-d902-4195-bf80-2e6518ad3c6d")
                        },
                        new
                        {
                            Id = new Guid("3bed994a-cbee-4d60-b22f-a922b82eb841"),
                            BlockType = 7,
                            Content = "I'll have a double espresso. Make it strong.",
                            CreatedAt = new DateTime(2026, 2, 8, 20, 23, 51, 404, DateTimeKind.Utc).AddTicks(9980),
                            LastModifiedAt = new DateTime(2026, 2, 8, 20, 23, 51, 404, DateTimeKind.Utc).AddTicks(9980),
                            OrderIndex = 3,
                            ScriptId = new Guid("36ca9b58-d902-4195-bf80-2e6518ad3c6d")
                        });
                });

            modelBuilder.Entity("Wrap.Data.Models.ShootingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.ToTable("ShootingDays");
                });

            modelBuilder.Entity("Wrap.Data.Models.ShootingDayScene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShootingDayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("ShootingDayId", "SceneId");

                    b.ToTable("ShootingDaysScenes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wrap.Data.Models.Cast", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", "User")
                        .WithMany("CastMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wrap.Data.Models.Crew", b =>
                {
                    b.HasOne("Wrap.Data.Models.Infrastructure.ApplicationUser", "User")
                        .WithMany("CrewMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wrap.Data.Models.CrewSkill", b =>
                {
                    b.HasOne("Wrap.Data.Models.Crew", "CrewMember")
                        .WithMany("Skills")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewMember");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.ProductionCast", b =>
                {
                    b.HasOne("Wrap.Data.Models.Cast", "CastMember")
                        .WithMany("CastMemberProductions")
                        .HasForeignKey("CastMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithMany("ProductionCastMembers")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CastMember");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.ProductionCrew", b =>
                {
                    b.HasOne("Wrap.Data.Models.Crew", "CrewMember")
                        .WithMany("CrewMemberProductions")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithMany("ProductionCrewMembers")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewMember");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.SceneCast", b =>
                {
                    b.HasOne("Wrap.Data.Models.Cast", "CastMember")
                        .WithMany("CastMemberScenes")
                        .HasForeignKey("CastMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.Scene", "Scene")
                        .WithMany("SceneCastMembers")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CastMember");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Wrap.Data.Models.MappingEntities.SceneCrew", b =>
                {
                    b.HasOne("Wrap.Data.Models.Crew", "CrewMember")
                        .WithMany("CrewMemberScenes")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.Scene", "Scene")
                        .WithMany("SceneCrewMembers")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewMember");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Wrap.Data.Models.ProductionAsset", b =>
                {
                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithMany("ProductionAssets")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.Scene", b =>
                {
                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithMany("Scenes")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.Script", b =>
                {
                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithOne("Script")
                        .HasForeignKey("Wrap.Data.Models.Script", "ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.ScriptBlock", b =>
                {
                    b.HasOne("Wrap.Data.Models.Script", "Script")
                        .WithMany("ScriptBlocks")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Script");
                });

            modelBuilder.Entity("Wrap.Data.Models.ShootingDay", b =>
                {
                    b.HasOne("Wrap.Data.Models.Production", "Production")
                        .WithMany("ShootingDays")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Wrap.Data.Models.ShootingDayScene", b =>
                {
                    b.HasOne("Wrap.Data.Models.Scene", "Scene")
                        .WithMany("ShootingDayScenes")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Wrap.Data.Models.ShootingDay", "ShootingDay")
                        .WithMany("ShootingDayScenes")
                        .HasForeignKey("ShootingDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");

                    b.Navigation("ShootingDay");
                });

            modelBuilder.Entity("Wrap.Data.Models.Cast", b =>
                {
                    b.Navigation("CastMemberProductions");

                    b.Navigation("CastMemberScenes");
                });

            modelBuilder.Entity("Wrap.Data.Models.Crew", b =>
                {
                    b.Navigation("CrewMemberProductions");

                    b.Navigation("CrewMemberScenes");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Wrap.Data.Models.Infrastructure.ApplicationUser", b =>
                {
                    b.Navigation("CastMembers");

                    b.Navigation("CrewMembers");
                });

            modelBuilder.Entity("Wrap.Data.Models.Production", b =>
                {
                    b.Navigation("ProductionAssets");

                    b.Navigation("ProductionCastMembers");

                    b.Navigation("ProductionCrewMembers");

                    b.Navigation("Scenes");

                    b.Navigation("Script");

                    b.Navigation("ShootingDays");
                });

            modelBuilder.Entity("Wrap.Data.Models.Scene", b =>
                {
                    b.Navigation("SceneCastMembers");

                    b.Navigation("SceneCrewMembers");

                    b.Navigation("ShootingDayScenes");
                });

            modelBuilder.Entity("Wrap.Data.Models.Script", b =>
                {
                    b.Navigation("ScriptBlocks");
                });

            modelBuilder.Entity("Wrap.Data.Models.ShootingDay", b =>
                {
                    b.Navigation("ShootingDayScenes");
                });
#pragma warning restore 612, 618
        }
    }
}
